#!/bin/bash

set -e # to exit as soon as there is an error

#opam_version=2.2.1
#dune_version=3.20.2
#make_version=4.3

hollight_version=3.1.0
hollight_commit=Release-3.1.0
hol2dk_commit=2.1.0
lambdapi_commit=3.0.0
camlp5_version=8.03.06
ocaml_version=5.3.0
rocq_version=9.0.0

usage() {
    cat <<__EOF__
usage: `basename $0` \$library [\$stage]

arguments:
- \$library: one of Real_With_nat, Real_With_N, HOL, Multivariate, Unif or Logic
- stage: optional integer specifying at which point to start the script

effects in a temporary directory ./tmp: 
stage 1: create an opam switch
stage 2: install hol-light's dependencies
stage 3: install lambdapi $lambdapi_commit
stage 4: install rocq-prover $rocq_version
stage 5: install this repository's dependencies (mathcomp, equations)
stage 6: install hol2dk $hol2dk_commit
stage 7: install hol-light
stage 8: patch_hollight
stage 9: dump_proofs
stage 10: configure a tmp/output directory
stage 11 create and check opam library in tmp/opam
stage 12 compare opam files
stage 13 translate proofs in tmp/output
stage 14 check proofs
__EOF__
}

error() {
    echo error: $1
    echo
    usage
    exit 1
}

library="$1"

# The file to translate
case $library in
    Real_With_N|Real_With_nat)
        hollight_file=hol_upto_real.ml;;
    HOL)
        hollight_file=hol.ml;;
    Multivariate)
        hollight_file=Multivariate/make_complex.ml;;
    Unif)
        hollight_file=Logic/make_upto_unif.ml;;
    Logic)
        hollight_file=Logic/make.ml;;
    "")
        error "library argument expected";;
    *)
        error "unknown library name: $library";;
esac

# dump-simp-before-hol for everything included in hol.ml
case $library in
    Real_With_N|Real_With_nat|HOL)
        dump_simp_option=-before-hol;;
    *)
        dump_simp_option= ;;
esac
        
# The dependencies
case $library in
    Real_With_N)
        require="Stdlib.NArith.BinNat mathcomp.classical.classical_sets";;
    Real_With_nat)
        require="mathcomp.boot.ssrnat mathcomp.boot.div mathcomp.boot.seq";;
    *)
        require="Stdlib.Reals.Reals mathcomp.boot.ssrnat mathcomp.boot.div mathcomp.boot.seq mathcomp.algebra.ssralg mathcomp.algebra.ssrint mathcomp.algebra.intdiv mathcomp.classical.classical_sets mathcomp.classical.cardinality mathcomp.analysis_stdlib.Rstruct_topology";;
esac

# The mappings files for Real_With_N are specific
case $library in
    Real_With_N)
        vfiles="$library/type.v $library/mappings.v"
        mkfile="$library/mappings.mk";;
    *)
        vfiles=$library/mappings.v
        mkfile= ;;
esac

base=`basename $hollight_file .ml`
lpfile=$library/mappings.lp
root_path=HOLLight.$library
jobs='-j32'

# we prefix $lpfile, $vfiles and $mkfile with "../../"
lpfile=../../$lpfile
if test -n "$mkfile"; then mkfile=../../$mkfile; fi
for f in $vfiles; do files="$files ../../$f"; done
vfiles=$files

mkdir -p tmp
cd tmp

if test -n "$2"
then
    stage=$2
else
    if test -f STAGE
    then
        stage=`head -n1 STAGE` # last completed stage
        stage=`expr $stage + 1`
    else
        stage=1
    fi
fi

line() { echo '------------------------------------------------------------'; }

start() {
    line
    echo STAGE $stage: $* ...
}

#usage: checkout_commit url commit
checkout_commit() {
    d=`basename $1 .git`
    start install $d
    git clone $1
    cd $d
    git checkout $2
    cd ..
}

#usage: install package_name version
install() {
    start install $1
    opam install -y $1.$2
}

create_opam_switch() {
    start create opam switch
    opam update
    opam switch create . $ocaml_version
}

install_hollight_deps() {
    start install HOL-Light dependencies
    opam pin -y camlp5 $camlp5_version
    opam install -y --deps-only hol_light.$hollight_version
}

install_lambdapi() {
    checkout_commit https://github.com/Deducteam/lambdapi.git $lambdapi_commit
    cd lambdapi
    git checkout -b reproduce
    opam install -y .
    cd ..
}

install_deps() {
    start install dependencies
    opam repo add rocq-released https://rocq-prover.org/opam/released
    opam install -y .. #TODO: do not know if there is something better to do than to install the library for dependencies between files. 
}

install_hol2dk() {
    checkout_commit https://github.com/Deducteam/hol2dk.git $hol2dk_commit
    cd hol2dk
    dune build && dune install
    cd ..
}

install_hollight() {
    checkout_commit https://github.com/jrh13/hol-light.git $hollight_commit
    cd hol-light
    make
    cd ..
}

patch_hollight() {
    start patch hol-light
    hol2dk patch
}

gen_hollight_file() {
    case $library in
        Real_With_N|Real_With_nat)
            awk "/^loads \"real.ml\"/{print;RM=1;next}/^loads /{if(RM)next}{print}" hol_lib.ml > hol_lib_upto_real.ml
            sed -e "s/hol_lib.ml/hol_lib_upto_real.ml/" hol.ml > $hollight_file;;
        Unif)
            awk '/^loadt "Logic\/unif.ml"/{print;RM=1;next}/^loadt /{if(RM)next}{print}' Logic/make.ml > $hollight_file;;
        *);;
    esac       
}

dump_proofs() {
    start dump hol-light proofs
    cd hol-light
    gen_hollight_file
    hol2dk dump-simp$dump_simp_option $hollight_file
    cd ..
}

config_output_dir() {
    start configure output directory
    mkdir -p output
    cd output
    if test -f Makefile; then make $jobs clean-all; fi
    hol2dk config $hollight_file $root_path $require $vfiles $mkfile $lpfile
    cd ..
}

translate_proofs() {
    start translate HOL-Light proofs to lambdapi and rocq
    cd output
    make split
    make $jobs lp
    make $jobs v
    make $jobs merge-spec-files
    make $jobs rm-empty-deps
    cd ..
}

check_proofs() {
    start check proofs
    cd output
    make $jobs vo
    cd ..
}

remove_empty_modules() {
    sed -e "s/${base}_//g" \
        -e "/^Require \(Im\|Ex\)port ${root_path}\.theory_hol\.$/d" \
        -e "/^Require \(Im\|Ex\)port ${root_path}\.types\.$/d" \
        -e "/^Require \(Im\|Ex\)port ${root_path}\.axioms\.$/d" \
        $1
}

create_and_check_opam_library() {
    start create opam library
    cd output
    make $jobs opam
    cd ..
    mkdir -p opam
    cd opam
    if test -f Makefile; then make $jobs clean; fi
    cp ../../opam $vfiles $mkfile .
    sed -e "s/HOLLight/HOLLight.$library/" ../../Makefile > Makefile
    remove_empty_modules ../output/${base}_terms.v > terms.v
    remove_empty_modules ../output/${base}_opam.v > theorems.v
    make $jobs
    cd ..
}

compare_opam_file() {
    line
    echo compare $1 ...
    diff ../$library/$1 opam/$1
}

compare_opam_files() {
    for f in terms.v theorems.v
    do
        compare_opam_file $f
    done
}

stage() {
    if test $1 -eq $stage
    then
        shift
        $*
        echo $stage > STAGE
        stage=`expr $stage + 1`
    fi
}

stage 1 create_opam_switch
eval `opam env`
stage 2 install_hollight_deps
stage 3 install lambdapi $lambdapi_commit
stage 4 install rocq-prover $rocq_version
stage 5 install_deps
stage 6 install hol2dk $hol2dk_commit
#export HOL2DK_DIR=`pwd`/hol2dk
export HOL2DK_DIR=$OPAM_SWITCH_PREFIX/share/hol2dk
stage 7 install_hollight
export HOLLIGHT_DIR=`pwd`/hol-light
stage 8 patch_hollight
stage 9 dump_proofs
stage 10 config_output_dir
stage 11 create_and_check_opam_library
stage 12 compare_opam_files
stage 13 translate_proofs
stage 14 check_proofs